### ISSUE TITLE
error in multi-GPU training

### ISSUE THREAD

**Issue by shwetgarg** [allenai/bi-att-flow#14]
I am able to train the model on cpu. But when I am trying to train it on multi gpu with following command:
python -m basic.cli --mode train --noload --num_gpus 3 --batch_size 20
it is throwing following error:
ValueError: Variable model_1/model_1/loss/ExponentialMovingAverage/biased does not exist, or was not created with tf.get_variable(). Did you mean to set reuse=None in VarScope?

I tried searching it on internet, but being new to tensorflow, could not figure out where to make the fix. Any pointer will be helpful.

**Comment by webeng** [comment]
Have you tried with one GPU?

**Comment by seominjoon** [comment]
I think you are using tensorflow v1.0. I had this error too with the newer version. For now, please use v0.11.

**Comment by wenwei202** [comment]
How could this issue be closed without fixing it? Training in multi-GPU mode using tensorflow 1.1.0 still has issues because of variable sharing.
```
ValueError: Attempt to have a second RNNCell use the weights of a variable scope that already has weights: 'prepro/u1/fw/basic_lstm_cell'; and the cell was not constructed as BasicLSTMCell(..., reuse=True).  To share the weights of an RNNCell, simply reuse it in your second calculation, or create a new one with the argument reuse=True.
```

**Comment by wenwei202** [comment]
Fixed in the this [commit](https://github.com/wenwei202/bi-att-flow/commit/7ddf2563133313b36b8eb6364aba9a3f6f63ace1). @seominjoon please check.

**Comment by guotong1988** [comment]
@wenwei202 Thank you, But.
ValueError: Variable emb/emb_var/char_emb_mat/Adam/ does not exist, or was not created with tf.get_variable(). Did you mean to set reuse=None in VarScope?
