### ISSUE TITLE
prepro.py default not splitting sentences?

### ISSUE THREAD

**Issue by JunweiLiang** [allenai/bi-att-flow#17]
Hi, I follow the preprocessing example you provide. But in the output the sentences are not separated unless I add the "--split" flag. I wonder if you train the official model in this way as well?

**Comment by seominjoon** [comment]
My Nov. 4 model did "split", while Nov. 27 model does not split. I saw a small yet significant improvement when I do not split. But split could be useful for faster training (because longer LSTM takes longer time), hence ideal for fast iteration during tuning. I hope that helped!
