### ISSUE TITLE
Limits on size of paragraph/query?

### ISSUE THREAD

**Issue by bluelight773** [allenai/bi-att-flow#28]
Hello, when using the demo (with the pretrained model) to run against new paragraphs/queries, 1) what limits apply on the length of paragraph and/or query?

I do see in basic/demo_cli.py that it seems the following parameters are set:
flags.DEFINE_integer("word_count_th", 30, "word count th [100]")
flags.DEFINE_integer("char_count_th", 150, "char count th [500]")
flags.DEFINE_integer("sent_size_th", 1000, "sent size th [64]")
flags.DEFINE_integer("num_sents_th", 1000, "num sents th [8]")
flags.DEFINE_integer("ques_size_th", 100, "ques size th [32]")
flags.DEFINE_integer("word_size_th", 48, "word size th [16]")
flags.DEFINE_integer("para_size_th", 1000, "para size th [256]")

Meanwhile these values are set differently in basic/demo_cli.py.

2) Is it just the values in basic/demo_cli.py that we care about when running the demo (ie: basic/cli.py flags won't have an effect even if they'd been used to build the model)?

3) What does each of these numbers entail exactly as it's not obvious in all cases?

4) And can one change those values in basic/demo_cli.py) to any desired number and have them take effect as soon as the demo server is up? 

5) Is there a practical way to let any length of paragraph/query be accepted?

Note there is overlap between the concerns raised here and what's brought up on issue 13 and so I've just raised some of the above questions there as well.  Happy to have questions answered within either issue.

Thank you

**Comment by seominjoon** [comment]
1. The only restrictions to those sizes is GPU RAM size (or time if you run on CPU).
2. basic/cli.py won't have an effect when running demo.
3. Please see my response in the other issue!
4. Yes, you can.
5. If you set it to really high value, yes, but it will either cause GPU out of memory or will take a long time for long input.
