### ISSUE TITLE
Make use of part of speech(pos)

### ISSUE THREAD

**Issue by rubby33** [allenai/bi-att-flow#29]
Hi, @seominjoon 

Do you have try to use the part of speech(pos)?
Because the same word may have different pos, it may increase the performance of bi-att-flow. 

If i want to make use of pos besides  word embedding and character embedding, could you give me some advise? Thank you so much.

**Comment by seominjoon** [comment]
Hi @rubby33 ,
POS can be helpful, but I have never used it.
probably the best way to do it is create a new input placeholder (in addition to 'x', 'cx', etc.) that accepts these POS tags (you will need to preprocess them of course), and then use it in the model as a word with embedding_lookup.
