### ISSUE TITLE
Clearer description on EM and F1 result would be helpful for reproduction 

### ISSUE THREAD

**Issue by insikk** [allenai/bi-att-flow#31]
Hello. 
Thank you for sharing well-written source code repository. By the way, I had confusion when I was trying to reproduce your result because the EM and F1 score on dev set during training are lower than the score you provided. After few days of muddling through, I realized you mentioned it in README.

> Note that the printed scores are not official (our scoring scheme is a bit harsher). To obtain the official number, use the official evaluator (copied in squad folder) and the output json file.

It is easy to miss the above comment. I suggest more clarification on README would be really helpful for others also. I made a [pull request](https://github.com/allenai/bi-att-flow/pull/32) for the updated README.

Is there any reason that you used harsher scoring scheme instead of the squad's evaluation method? Does it help to increase model performance?

**Comment by wenwei202** [comment]
@insikk I tried the default scripts in the dev branch and seems it overfits after 7K steps. See the issue #36 . Is it also the result you get? Not sure if I did something wrong.

**Comment by insikk** [comment]
@wenwei202 yes. I also see overfit on reproduction. In my case with batch size 60. I get the best score at 9k. It gives 67.56 em and 77.13 f1 score. I think you did it right.

**Comment by seominjoon** [comment]
Hi @insikk ,
Thanks for clarifying the readme file. I just merged it.
In dev data, the optimizer seems to work much better that it achieves the peak very fast (and after that it overfits). peak at 7k seems to be right.
