### ISSUE TITLE
Understanding the meaning of TimeStep in Attention Layer

### ISSUE THREAD

**Issue by ukrrish** [allenai/bi-att-flow#33]
Hi Guys,
I’ve been going through your paper on BI-DIRECTIONAL ATTENTION FLOW FOR MACHINE COMPREHENSION and I’m amazed to say the least. I’ve have been trying to implement the architecture proposed by you but I have a road-block in understanding a particular line/sentence that has been re-iterated within the paper.
” The attention vector at each time step, along with the embeddings from previous layers, are allowed to flow through to the subsequent modeling layer.” 

My understanding of this line is two fold :

- By each time step you mean to say that the shared similarity matrix is updated as in when a new word output from LSTM comes into the attention layer.At (t = t) the shared similarity matrix S is different from S (t = t+1).If yes, how do I visualize the output at the end of t=t timestep.
- OR, is it just another way of saying return_sequences=True and the rest would be taken care by the KERAS Layer.

I’m trying to implement the architecture in Python using KERAS layers.Any help is highly appreciated. 
Thank you for your valuable time.

**Comment by seominjoon** [comment]
Hi @ukrrish ,
There is only one Similarity matrix, which can be considered as the outer product of context LSTM outputs and quesiton LSTM outputs. The matrix is not updated at every time step.
Thanks!
