### ISSUE TITLE
AttributeError: 'int' object has no attribute 'summaries'

### ISSUE THREAD

**Issue by Matrixsun** [allenai/bi-att-flow#34]
I am a new  . when I run the skim script as README.md . I get a error  follow:
  File "basic/main.py", line 119, in _train
    graph_handler.add_summaries(e_train.summaries, global_step)
AttributeError: 'int' object has no attribute 'summaries'

my tensorflow version is 1.1.0

**Comment by RishabGoel** [comment]
@Matrixsun I had a similar error. Just comment those lines and then run. This is of course, if you want to just run it and see the results.

**Comment by Matrixsun** [comment]
My script is stopping  when I get the error , then I use python3 ,the error is disappeared.I do not konw  why python3 is ok ,python2 is bad for this error.

**Comment by RishabGoel** [comment]
It might be the return type issue.

**Comment by zww847204326** [comment]
What's the version of your tensorflow when you run in python3 enviroment.,tensorflow0.11 can not be installed in this platform.
