### ISSUE TITLE
Examples are not fully loaded

### ISSUE THREAD

**Issue by wenwei202** [allenai/bi-att-flow#35]
I run 
`python -m basic.cli --mode train --noload --debug` and get
```
Loaded 85277/87599 examples from train
Loaded 10258/10570 examples from dev
...
```
Seems examples are not fully loaded. Why may be the issue?

**Comment by insikk** [comment]
When the the main.py load data, it has filter. So it won't load, for example, too long sentence containing passage question pair. You can change threshold in cli.py

**Comment by ObiJiang** [comment]
@insikk What filter size did you use to achieve the accuracy you got? I am having problem reproducing the EM and F1 score as presented in the paper.

**Comment by wenwei202** [comment]
@ObiJiang 
I am enable to duplicate the results now.
Some errors popped up when I was generating the dataset, and I just rerun the scripts without removing the first generated "bad?" dataset, hoping it could overwrite the original ones.
After cleaning up the bad ones and re-generate the dataset, I get (I am using the default configurations)
```
Loaded 87442/87599 examples from train
Loaded 10540/10570 examples from dev
```

More info in #36

**Comment by ObiJiang** [comment]
I am using the default configuration as well. But for some reason, I am getting different number of loaded examples? Strange!

**Comment by wenwei202** [comment]
@ObiJiang different run, different loaded number of examples too
