### ISSUE TITLE
where is the "Character Embedding Layer" in code

### ISSUE THREAD

**Issue by Matrixsun** [allenai/bi-att-flow#37]
hi  
     I am a new coder. I am very interested in  BiDAF. but when I had read ./squad/prepro.py ,not found  "Character Embedding Layer" code . Just see "Word Embedding Layer". Could you tell me:which  $name.py includes  the  "Character Embedding Layer".

**Comment by wenwei202** [comment]
It is [here](https://github.com/allenai/bi-att-flow/blob/master/basic/model.py#L81), and [conv](https://github.com/allenai/bi-att-flow/blob/master/basic/model.py#L95).

**Comment by Matrixsun** [comment]
@wenwei202  Thank you!
