### ISSUE TITLE
Do I need to consider number of sentences in a paragraph?

### ISSUE THREAD

**Issue by Taekyoon** [allenai/bi-att-flow#38]
I'm really interested in your model, so I'm trying to implement the model on pytorch.
But there's a problem, during reconstructing your model, I found that the dimension for number of sentence exists, whereas in your paper, as long as I read there never mentioned about this dimension. I'm aiming to implement the model for Squad dataset, and carefully think about why this dimension was needed? So, I want to ask you 'Can this dimension be useful?' and 'Why did you add this dimension?'

**Comment by seominjoon** [comment]
Hi @Taekyoon ,
Good point, and actually the number of sentences is not used.
That is, M = 1 in the preprocessing script and the entire paragraph is considered as a single sequence of words without sentence-splitting.

The reason why I have dimension is, though, that it is useful for tuning hyperparams by speeding up the training process. If I split the paragraph by sentences it reduces the length of LSTM that the model can be trained much faster (2~3 times faster usually). But at the end considering the paragraph as a single sequence gives 0.5~1% improvement.

**Comment by Taekyoon** [comment]
Thanks a lot!
