### ISSUE TITLE
Error from graph_handler

### ISSUE THREAD

**Issue by Palang2014** [allenai/bi-att-flow#5]
Thanks for the great work and for sharing the codes.

I am trying to reproduce your single model results. Following the steps you have described, I tried:
```
python -m basic.cli --mode train --noload --len_opt --cluster
```
Everything worked fine till 4% of training, then I got the following error from `graph_handler`:
```
File "basic/main.py", line 117, in _train
graph_handler.add_summaries(e_train.summaries, global_step)
AttributeError: 'int' object has no attribute 'summaries'
```

It looks like it is from TF, not sure, any ideas how I can resolve this?

Thanks!
Hamid

**Comment by Palang2014** [comment]
The source of problem was that I was trying it with Python 2.7. 
Used Python 3.5 and the problem resolved. 
Closing this issue now!

**Comment by lmthang** [comment]
Hi,

Just a comment. If one wants to use Python 2.7, apart from other minor fixes, there's one important thing to take note. There is a bug (under Python 2.7) in the method ```get_batches``` of file ```basic/read_data.py```. Instead of:

```python
num_epochs = int(math.ceil(num_batches / num_batches_per_epoch))
```
It should be:
```
num_epochs = int(math.ceil(float(num_batches) / num_batches_per_epoch))
```
This will make sure ```num_epochs=1``` when ```num_batches < num_batches_per_epoch```.

-Thang

**Comment by Palang2014** [comment]
Hi Thang,

Thanks for sharing this fix. 

Were you able to regenerate the results using Python 2.7 after resolving this bug? I was able to regenerate them using Python 3.5 but not Python 2.7.

Thanks!
Hamid

**Comment by lmthang** [comment]
Hi Hamid,

I'll share with you later once I got everything solved. When you say, you can regenerate using Python 3.5. Does it mean the below code will give you around 77% F1 for single model?
```bash
python -m basic.cli --mode train --noload --len_opt --cluster
python -m basic.cli --len_opt --cluster
```
-Thang

**Comment by Palang2014** [comment]
Hi Thang,

Very good, thanks!

Above commands gave me 74.6% F1 for single model. But this is not official F1 as they have explained it is their own scoring system. When I used official evaluator as: 
```python
python squad/evaluate-v1.1.py $HOME/data/squad/dev-v1.1.json out/basic/00/answer/test-020000.json
```
I got ~ 76.4% F1 for single model which is pretty close to the official one that is reported.

Thanks!
Hamid

**Comment by lmthang** [comment]
Hi Hamid,

Do you happen to know if you still get similar results with Python 3 when using either Tensorflow 0.12 or smaller batch sizes? I obtained ~ 68% F1 with Python3, Tensorflow 0.12, batch size 40.

Thanks,
-Thang

**Comment by Palang2014** [comment]
Hi Thang,

My tensorflow version is 0.12.0. I used default batch size which is 60 I guess. Why you decreased it to 40, because of GPU memory? If your GPU memory is around 12 G it should work fine with batch size 60. The whole training will be finished less than one day. But if you decrease batch size, I guess you might need to fine tune hyper-params again, e.g., I do not know if they normalize step size w.r.t batch size in their code, etc. I did not do any fine tuning though.

Hope this helps you.
Hamid

**Comment by lmthang** [comment]
Thanks for the info, Hamid! Good to know that you can reproduce with TF 0.12.0. Yes, it was due to memory since I was testing quickly on a local GTX1080 with 8G of memory.

**Comment by lmthang** [comment]
Hi Hamid,

I confirmed that I can reproduce your results 74.7% F1 (with their own unofficial evaluation) using the default settings. (Earlier, I was preprocessing the data using Python 2 which might have cause some problems).

Thanks!
-Thang

**Comment by Palang2014** [comment]
Thanks for the update and glad to hear that you got the same result.

Thanks!
Hamid

**Comment by Palang2014** [comment]
Hi Thang,

I am trying to resume training from an specific step using something like:
```
python -m basic.cli --mode train --load True --load_step 17000 --len_opt --cluster --batch_size 40 --run_id 8
```
but it either starts from step 0 or gives an error. I checked the "save" folder, there is a TF checkpoint but I do not want to re-train from last epoch but from an intermediate epoch. Have you done this? If yes, can you please share the code snippet?

Other files there are in the format, e.g., "basic-17000.meta", "basic-17000.index", "basic-17000.data-00000-of-00001".

Thanks!
Hamid

**Comment by Palang2014** [comment]
Resolved!
