### ISSUE TITLE
basic_cnn too much gpu memory?

### ISSUE THREAD

**Issue by liyi193328** [allenai/bi-att-flow#7]
Hi, 
when training squad(basic.cli) dataset, Titan x 's 12 gpu memory is enough,  config.max_sent_size = min(config.max_num_sents, config.num_sents_th), and config.max_sent_size is 1 because of sent_tokenize = lambda para: [para]

while training cnn (basic_cnn.cli) dataset, config.max_sent_size = 11, config.max_num_sents = 200, which results to gpu memory error.

Any ideas to fix it( may reduct the config.max_num_sents in parser) or do like in squad? Thanks!

**Comment by seominjoon** [comment]
Hi, sorry for late response; apparently I was not watching this repo and I just realized it (the repo is owned by AI2, not me).
Could you use `basic_cnn` in `tqa` branch? It has instructions for running experiments on CNN/DailyMail. I will merge `tqa` into master soon, but right now master's `basic_cnn` is broken.. 
By the way, as I have mentioned in the paper, I had to use 8 GPUs to train on CNN/DailyMail dataset. The instruction at `tqa` branch will be clear about this setup. Thanks!

**Comment by liyi193328** [comment]
@seominjoon Nice to you, Much Thanks.
