### ISSUE TITLE
Assert error in squad/prepro.py

### ISSUE THREAD

**Issue by griff4692** [allenai/bi-att-flow#9]
<img width="463" alt="screen shot 2017-02-21 at 1 53 08 pm" src="https://cloud.githubusercontent.com/assets/12277915/23179809/2af1035e-f83d-11e6-9c7f-b1892ee65cc4.png">

How should I deal with this error? Thanks!

If I comment out that line, it ends up just failing on another similar assert statement...

**Comment by seominjoon** [comment]
Hi, sorry for late response!
The issue might be easily resolved with Python 3 (it seems you are using Python 2). Could you try with Python 3 and let me know if it works?

**Comment by rubby33** [comment]
with python3. everything is fine.
